### ISSUE TITLE
Issue with Traininng a new model or Applying the existing model for 3 band RGB images.

### ISSUE THREAD

**Issue by richiedlon** [jonathanventura/urban-tree-detection#1]
### Problem Description
I encountered an issue when attempting to apply an existing model to an RGB image. The error message received is as follows:

### Workaround Attempted

To resolve this issue, I tried training a new model using only 3-band RGB images (Created a new tif file with the given dataset by extracting RGB images only). However, the same error still persists when applying the model to RGB images.

### Expected Behavior

I expect that applying the model to 3-band RGB images should work without errors, as it does for 4-band images.

### Steps to Reproduce

1. Train a model using 3-band RGB images.
2. Attempt to apply the trained model to an RGB image.
3. Observe the `IndexError` mentioned above.

```
  File "/urban-tree-detection-main/utils/inference.py", line 32, in _tiled_inference
    image = src.read([1,2,3,4],window=window)
  File "rasterio/_io.pyx", line 533, in rasterio._io.DatasetReaderBase.read
IndexError: band index 4 out of range (not in (1, 2, 3))
```

### Additional Information

- The model performs as expected with 4-band images, but not with 3-band RGB images.

**Comment by jonathanventura** [comment]
Did you use the flag `--bands RGB` when running the `inference.py` script?

**Comment by jonathanventura** [comment]
Thank you for raising this issue!  I just pushed some corrections to the inference script which I think should fix the issue.  Let me know how it looks.  Also, I realized the inference script is not using the optimized hyperparameters -- I will fix that as well.

**Comment by richiedlon** [comment]
Yeah I did that. I tried directly train from the training dataset and apply
the inference. Additionally, I created a separate RGB set of images by
removing the NIR  band. But the error still persists during inference stage.
